[package]
name = "rust_edge"
version = "0.1.0"
authors = ["andrewgremlich <andrew.gremlich@ldschurch.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.6.5"
